title: <p align="center"> Madhur Gupta </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/madhur-gupta/">LinkedIn</a> |
  <a href="https://github.com/guptamadhur">GitHub</a>
  
  <br>   
  I'm a fullstack developer, working with the web on solutions related to data (like user personalization) and apps (with ReactJs and React Native), along with RESTful server services (using Python Django).
  I have a bachelor's degree in Computer Science Engineering and I'm currently working with JP Morgan Chase, India.
  <br>
  </p>

show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
